### ISSUE TITLE
Path substitutions?

### ISSUE THREAD

**Issue by fraguada** [microsoft/vscode-dwarf-debugging-ext#7] opened 2024-07-15 20:42 UTC
In the Chrome Dev tools extension I can use Path substitutions to map from the prefix in the wasm file to where the actual source files are on my hard drive. this works great in the Chrome extension. I can build locally or on our automated runners and map the wasm to the source files. 

Does such a feature exist with the vs code extension?

**Comment by damian-prom** [comment] 2024-09-26 00:24
I would like that too.

I tried with `sourceMapPathOverrides` settings in launch configuration, but without any successed.

I compile my C++ code with flag: `"-fdebug-compilation-dir=/root"` (It is required, because my build system is a bazel with sandboxing),
and I want to map `/root` to `"${workspaceFolder}"`.

**Comment by damian-prom** [comment] 2024-09-26 00:27
cc: @connor4312

**Comment by trzeciak** [comment] 2024-09-26 03:55
I would like that too.

I tried with `sourceMapPathOverrides` settings in launch configuration, but without any successed.

I compile my C++ code with flag: `"-fdebug-compilation-dir=/root"` (It is required, because my build system is a bazel with sandboxing),
and I want to map `/root` to `"${workspaceFolder}"`.

cc: @connor4312

**Comment by connor4312** [comment] 2024-09-26 18:20
sourceMapPathOverrides _should_ work but I admit it's been a moment since I tested it with DWARF stuff.

Can you add `trace: true` to your launch.json config and share the log file (location written to the Debug Console) here or to connor [at] xbox.com? Thanks!

**Comment by trzeciak** [comment] 2024-09-27 14:43
Hey, I wasn't sure if this project was alive xD, but now that I know!
I'll try to prepare a working (or rather not working xD) example that should be easy to reproduce locally, I'll do my best to prepare it this weekend.

**Comment by trzeciak** [comment] 2024-10-03 23:59
Finally.. xD
I prepared small example: https://github.com/trzeciak/vscode-debugging-webapp-wasm

Motivation:
In the target project I'm working on, we use [Bazel with the sandboxing](https://bazel.build/docs/sandboxing) to build C++,
so for debugging symbols to be useful we need to set the option [`-fdebug-compilation-dir=<some-root-pach>`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fdebug-compilation-dir) in clang (or equivalent option).
On the other hand, we build builds on CI, so we chose a common root folder, e.g.: `/ciroot`.
Let me know if you can repeat this in the prepared example, if not I will send my logs.
BTW: I working on macOS.

If I using [C/C++ DevTools Support (DWARF)](https://chromewebstore.google.com/detail/cc++-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb) in google chrome, and setup `Path substitutions` in extension-options, the breakpoints in tevtools works correctly with `/ciroot` path.

**Comment by trzeciak** [comment] 2024-10-21 10:01
@connor4312 : Any suggestions, or maybe I should ask this question somewhere else?

**Comment by connor4312** [comment] 2024-10-21 19:26
Thanks for the repro, fixed in the next [nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension). The source map path override `"file:///ciroot/*": "${workspaceFolder}/*",` will work.

**Closed** 2024-10-21 19:55 UTC

**Comment by trzeciak** [comment] 2024-10-22 20:49
Thank you, I tested it and it works!
